### ISSUE TITLE
API das corretoras retorna 500

### ISSUE THREAD

**Issue by Kaue-Romero** [BrasilAPI/BrasilAPI#522]
O teste da API das corretoras está retornando 500 com o seguinte código:
`Error: File not found
    at getIntermediatorsFromZip (webpack-internal:///./services/cvm/corretoras.js:25:11)
    at getExchangesData (webpack-internal:///./services/cvm/corretoras.js:82:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Array.action (webpack-internal:///./pages/api/cvm/corretoras/v1/[cnpj].js:16:30)
{
  url: '/api/cvm/corretoras/v1/02332886000104',
  name: 'EXCHANGE_INTERNAL',
  status: 500,
  type: 'exchange_error',
  errors: []
}
`
Pois o arquivo na [url da função](https://dados.cvm.gov.br/dados/INTERMED/CAD/DADOS/cad_intermed.zip) com os dados das corretoras está vazio.
![Captura de tela de 2023-09-23 18-13-56](https://github.com/BrasilAPI/BrasilAPI/assets/69368947/c22739f3-8528-4c56-ae43-aba945f6c21f)
![Captura de tela de 2023-09-23 18-12-29](https://github.com/BrasilAPI/BrasilAPI/assets/69368947/0aaf3a61-dc5c-4c2e-b1ec-2eebeb19cac4)
![Captura de tela de 2023-09-23 18-12-51](https://github.com/BrasilAPI/BrasilAPI/assets/69368947/9d4e31f8-4af4-4047-b201-25a2e49428c2)

**Comment by lucianopf** [comment]
Resolvida — `/cvm/corretoras/v1` responde 200 hoje (lista completa de corretoras, validado 08/08/2026). O erro 'File not found at getIntermediatorsFromZip' foi corrigido desde set/2023.
